// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"backend-crowdfunding/campaign"
	"backend-crowdfunding/config"
	"backend-crowdfunding/database"
	"backend-crowdfunding/handler"
	"backend-crowdfunding/storage"
	"backend-crowdfunding/transaction"
	"backend-crowdfunding/user"
)

import (
	_ "backend-crowdfunding/docs"
)

// Injectors from wire.go:

func InitializeApp() (*App, error) {
	configConfig, err := config.Load()
	if err != nil {
		return nil, err
	}
	db, err := database.NewConnection(configConfig)
	if err != nil {
		return nil, err
	}
	repository := user.NewRepository(db)
	service := user.NewService(repository)
	authService := provideAuthService(configConfig)
	uploader, err := storage.New(configConfig)
	if err != nil {
		return nil, err
	}
	userHandler := handler.NewUserHandler(service, authService, uploader)
	campaignRepository := campaign.NewRepository(db)
	campaignService := campaign.NewService(campaignRepository)
	campaignHandler := handler.NewCampaignHandler(campaignService, uploader)
	transactionRepository := transaction.NewRepository(db)
	paymentService := providePaymentService(configConfig)
	gormTxRunner := transaction.NewTxRunner(db, transactionRepository, campaignRepository)
	transactionService := transaction.NewService(transactionRepository, campaignRepository, paymentService, gormTxRunner)
	transactionHandler := handler.NewTransactionHandler(transactionService)
	engine := newRouter(userHandler, campaignHandler, transactionHandler, authService, service)
	app := newApp(engine, configConfig)
	return app, nil
}
